### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by Dauntechino** [UBC-DSCI/ubc-dsci-minor-faq#1]
I'm a little confused as to the situation with 3rd/4th year students. You mention that applications are limited to second/third year standing students (in sciences) who are in their programs/majors, but at the same time your FAQ page mentions this:

"Thanks for your interest in the Data Science minor. I am sorry, but it is not open to students with 4th year standing in the fall of the year they apply." 

I'm currently at the end of my second year and I really want to apply for the minor, however, I lack one of the prerequisite courses mentioned under lower admissions requirements. In this case, does this mean I won't be able to apply in my third year (2022) since I'll be in fourth year standing during September of that year? A little confused as to who can apply, sorry.

**Comment by ttimbers** [comment]
Apologies for the confusion and thanks for your patience while we figure out the procedures and policies in the first year of offering the program. We will clarify the language on the website to make it clearer, so that it will soon read:

As of September 2021, applicants must already have a primary specialization, and be in year 2 or 3 standing of their undergraduate degree; applications will not be accepted once the student has gained 4th year standing.

Also, we will consider applications for students who take the pre-requisites in the summer, and they may be accepted with the condition that a minimum grade of 68% in the Data Science Minor lower-level requirements is obtained before September 2021. I will update the FAQ to reflect this.

Hope this answers your questions!

**Comment by Lourenzutti** [comment]
Hi @Dauntechino 

I am sorry for the confusion. Since this program involves different faculties, the requirements can be more confusing. 
Let me try to clarify.

As it turns out different faculties have different rules.
For example, the Faculty of Science allows third-year students to apply for the minor (even if you are going to be fourth-year in September). You cannot be fourth-year at the time of application, but you can be a forth-year at the start of the program. So, if you are in FoS, you should still be able to apply. If you are in a different faculty, e.g., Faculty of Arts, make sure that you satisfy the rules of the Faculty of Arts to apply for the minor.

Please let me know if you have any questions.
