### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by alexlin519** [UBC-DSCI/ubc-dsci-minor-faq#27]
To whom it may concern:
 
I am a mathematics student and I want to minor in data science. I will be in my third year in Sep. Thus I am only able to submit the science minor form in 2022 May.
 
However, DSCI 310(which I want to take in Sep this year) requires is:
*These seats are reserved for students who meet one of the following sets of restrictions:
1.    with one of these specializations: MIN DSCI

I am not able to register for the course and could you please help me to register for the course ignore the fact that I am not a DSCI minor. (But I will definitely take this minor next year, my GPA now is 87.7%)
An academic advisor would do that for me in detail.

Since I have a coop and my study term might be different. It is much more convenient  for me to register for the course this semester (in the future there might be no DSCI 310 in my study term since coop program has an unusual academic schedule and I will work from time to time )
 
 
Best,
Alex
55560361

**Comment by Lourenzutti** [comment]
Hi @alexlin519 

Sorry for the delay. 
No, unfortunately, I cannot give you priority based on your interest in applying for the data science minor next year. 

The seats are restricted because we are giving the minor students priority. Once they are registered, we will start registering students on the waitlist for the course. If you are interested, you should register for the waitlist. 

Let me know if you have further questions.

Cheers,
