### ISSUE TITLE
UBC Data Science minor question

### ISSUE THREAD

**Issue by lzung** [UBC-DSCI/ubc-dsci-minor-faq#9]
I understand that the Data Science minor program is not accepting students who will be in their 4th year by fall 2021 (I unfortunately applied very early on and was not aware of this restriction), but is it possible for students outside of the minor to take the new upper-level courses (DSCI 310, DSCI 320, CPSC 368) or are these seats going to be fairly restricted? I will have taken all lower-level prerequisites by September so I'm hoping that I can take these classes before graduating.

**Comment by Lourenzutti** [comment]
Hi @lzung,

I am sorry for the confusion.
As it turns out different faculties have different rules. 
For example, the Faculty of Science allows third-year students to apply for the minor (even if you are going to be fourth-year in September). You cannot be fourth-year at the time of application, but you can be a forth-year at the start of the program. So, if you are in FoS, you should still be able to apply. If you are in a different faculty, e.g., Faculty of Arts, make sure that you satisfy the rules of Faculty of Arts to apply for the minor. 

Please let me know if you have any questions.

**Comment by lzung** [comment]
Thank you for the clarification @Lourenzutti!

Unfortunately, and this might be a rare case, but I was promoted to 4th year in September 2020 and was on co-op for the duration of last year so I have already qualified for fourth-year standing which would make me ineligible (i.e. I'd be technically 5th year).

I did notice though that the FoS minor application does allow 4th year students to apply with a written appeal:
"Students that have gained fourth-year standing are not normally permitted to pursue a minor. Please submit a written appeal that references why you did not apply for the minor earlier, and what steps you will take to complete your degree program in a timely manner."

I'm curious about whether the restriction is specific to the Data Science minor or if fourth-year students may still be able to appeal?
